name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'main/go.mod'
          check-latest: true
      # - name: Checkout dependencies (your-repo)
      #   uses: actions/checkout@v3
      #   with:
      #     repository: your-user/your-repo
      #     ssh-key: ${{ secrets.YOUR_REPO_READONLY }}
      #     path: your-repo
      - name: Test packages
        run: make test
      - name: Build artifacts
        run: make build
